kind: Namespace
apiVersion: v1
metadata:
  name: todo-app

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-deployment
  namespace: todo-app
spec:
  revisionHistoryLimit: 2    # Keeps 2 old replicaSets
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-container
        image: wayneisbatman/django-todo-app:latest
        ports:
        - containerPort: 8000

        livenessProbe:
          httpGet:
            path: /todo
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /todo
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

        startupProbe:
          httpGet:
            path: /todo
            port: 8000
          failureThreshold: 30
          periodSeconds: 10