# This file defines Kubernetes services for todo application
kind: Service
apiVersion: v1
metadata:
  name: todo-service
  namespace: todo-app
spec:
  selector:
    app: todo-app
  type: NodePort       # Type of service, can be ClusterIP, NodePort, LoadBalancer, etc.
  ports:
    - protocol: TCP
      port: 8000         # Port on the service for internal cluster access
      targetPort: 8000   # Port on the container
      nodePort: 38000    # Port on the service for external access (must be between 30000–32767)


