kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: apache-hpa
  namespace: apache

spec:
  scaleTargetRef:
    kind: Deployment
    name: apache-deployment
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 6
  maxReplicas: 7

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30   # default is 300s
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        
